FROM alpine:3.7

## nginx web server
## php is for phpmyadmin
## procps enables pkill command
## openrc for sad reboot of nginx when launched (rc-update)
RUN apk add --no-cache nginx php procps

RUN ln -s /etc/init.d/nginx /bin

RUN mkdir /script

RUN echo "#!/bin/sh" > /script/launch.sh

RUN echo "mkdir -p run/nginx" >> /script/launch.sh

RUN echo "nginx" >> /script/launch.sh

RUN echo "/bin/sh" >> /script/launch.sh

RUN chmod +x /script/launch.sh

##RUN rc-update add nginx default

##RUN sh /etc/init.d/nginx

## RUN printf 'hellobebechat\n' | printf 'hellobebechat\n' | adduser USER
