apiVersion: v1
kind: Service
metadata:
  name: influxdb
  annotations:
    metallb.universe.tf/allow-shared-ip: shared ip
spec:
  type: ClusterIP
  selector:
    app: influxdb
  ports:
    - name: http
      port: 8086
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: influxdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: image-influxdb
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
        volumeMounts:
        - name: influxdb-data
          mountPath: /var/run/docker.sock
        - name: influxdb-pvs
          mountPath: /root/.influxdb/
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - 'echo "SHOW DATABASES;" | influx && pgrep telegraf'
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Always
      volumes:
      - name: influxdb-data
        hostPath:
          path: /var/run/docker.sock
      - name: influxdb-pvs
        persistentVolumeClaim:
          claimName: influxdb-pvc