apiVersion: 1

deleteDatasources:

  datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    user: grafana
    database: influxdb
    basicAuth: 1
    basicAuthUser: grafana
    isDefault: true
    jsonData:
      sslmode: "disable"
      httpMode: GET
    secureJsonData:
    version: 1
    editable: true