apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared ip
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
    - name: connection
      port: 21
      nodePort: 30021
    - name: datatransfer
      port: 30020
      nodePort: 30022
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: image-ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 30020
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - 'pgrep vsftpd'
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Always