apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: 172.17.0.2-172.17.0.2
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: image-nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - 'pgrep nginx'
      restartPolicy: Always